version: "3.7"
services:
  teslaspy:
    image: hub.rubyon.co.kr/teslaspy:latest
    container_name: teslaspy
    network_mode: host
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Asia/Seoul
      - ID=rubyon
      - PASSWORD=rubyon
    volumes:
      - ./cache.json:/app/cache.json
      - ./teslaspy_settings.json:/app/teslaspy_settings.json

  teslaspy-redis:
      container_name: teslaspy-redis
      image: redis:6-alpine
      command: redis-server --requirepass 'RubyOnStudio'
      restart: unless-stopped
      ports:
        - 1268:6379
      volumes:
        - ./redis:/data
