version: "3.7"
services:
  teslaspy:
    image: hub.rubyon.co.kr/teslaspy:latest
    container_name: teslaspy
    restart: unless-stopped
    tty: true
    ports:
      - 1267:1267
    environment:
      - TZ=Asia/Seoul
      - ID=rubyon
      - PASSWORD=password
    volumes:
      - ./cache.json:/app/cache.json
      - ./teslaspy_settings.json:/app/teslaspy_settings.json
    links:
      - teslaspy-redis
    depends_on:
      - teslaspy-redis

  teslaspy-redis:
      container_name: teslaspy-redis
      image: redis:6-alpine
      command: redis-server
      restart: unless-stopped
      volumes:
        - ./redis:/data
